### ISSUE TITLE
Play 2.4 version

### ISSUE THREAD

**Issue by nermin** [scalatest/scalatestplus-play#19]
Are there any plans to soon release a candidate version against 2.4.0-RC2 version of Play?
For example, `WSRequestHolder` has been renamed to `WSRequest`, as explained here:
https://www.playframework.com/documentation/2.4.0-RC2/Migration24

The current WsScalaTestClient references it:
https://github.com/scalatest/scalatestplus-play/blob/aef0c37632d70952393f889ac59bee7006b46f5c/src/main/scala/org/scalatestplus/play/WsScalaTestClient.scala#L39

**Comment by bvenners** [comment]
Hi Nermin,

Sure, we'll make a release for 2.4-RC2.

Bill

**Comment by DougC** [comment]
i've just raised  pull request #20 that fixes the problems in WsScalaTestClient and builds against 2.4.0-RC3

**Comment by bvenners** [comment]
This has been released as ScalaTest+Play 1.4.0-M2 (for Play 2.4.0-RC3 and ScalaTest 2.2.0). Please let us know if you have any problems with it.

**Comment by diwalak** [comment]
Has this been published ? I am not able to find this

**Comment by bvenners** [comment]
It is in Sonatype, so should be on Maven Central by now, here for 2.11:

https://oss.sonatype.org/content/groups/public/org/scalatestplus/play_2.11/1.4.0-M2/

And for 2.10, here:

https://oss.sonatype.org/content/groups/public/org/scalatestplus/play_2.10/1.4.0-M2/

**Comment by diwalak** [comment]
Hmm...I am getting an error probably due to a trailing space after M2 - `play_2.11-1.4.0-M2 .pom`
1.4.0-M1 resolves without any problem. Also, mvnrepository does not list this - http://mvnrepository.com/artifact/org.scalatestplus/play_2.11

```
[info] Resolving org.scalatestplus#play_2.11;1.4.0-M2  ...
[warn] 	module not found: org.scalatestplus#play_2.11;1.4.0-M2
[warn] ==== local: tried
[warn]   /Users/xyz/.ivy2/local/org.scalatestplus/play_2.11/1.4.0-M2 /ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatestplus/play_2.11/1.4.0-M2 /play_2.11-1.4.0-M2 .pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/scalatestplus/play_2.11/1.4.0-M2 /play_2.11-1.4.0-M2 .pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalatestplus#play_2.11;1.4.0-M2 : not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]

**Comment by bvenners** [comment]
Is that trailing space in your build file? Seems like it must be. The release does seem to have made it up to maven central:

http://search.maven.org/#artifactdetails|org.scalatestplus|play_2.11|1.4.0-M2|jar

**Comment by diwalak** [comment]
I changed nothing yet it now manages to resolve successfully. 
Thanks for your help.
