### ISSUE TITLE
Support using custom ApplicationLoader in addition to FakeApplication

### ISSUE THREAD

**Issue by rmmeans** [scalatest/scalatestplus-play#21]
With Play 2.4 it seems to me that it will be more common to use a custom application loader now to define your dependencies for your tests, etc than it will be to use a FakeApplication type.

The specs2 support built-in in play provides this via this helper:
https://github.com/playframework/playframework/blob/master/framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala#L25-L30

This becomes very handy when trying to use compile time DI with play 2.4 This sample product using specs2 shows how nice this can be: https://github.com/loicdescotte/play24SimpleDI

I would love to be able to do the same in using ScalaTest as we move our project DI to compile time. 

Perhaps this is already possible on the milestone and I'm just missing it? I'd like to be able to use a custom ApplicationLoader on something like OneAppPerSuite for example.

**Comment by bvenners** [comment]
Hy Ryan,

Something like that is on our list. We talked about this with James Roper at ScalaDays. Unfortunately we have been trying to get 3.0.0-RC1 out the door first, but after that we'll work on this. In the meantime PRs are welcomed with open arms if anyone has time to help.

Thanks.

Bill

**Comment by rmmeans** [comment]
Makes total sense! I know it's still a milestone release - just wasn't sure if it was going to be eventually addressed. Thanks for the good work!

**Comment by bvenners** [comment]
I have released 1.4.0-M4 with FakeApplication changed into Application. Please give it a try. If I don't hear back problems within a day or two, I'll release 1.4.0 final.

Thanks.

Bill

**Comment by rmmeans** [comment]
I don't have a working example I can quickly try this out with anymore, but I did review the recent commits and from first glance it does look like those changes will work to accomplish the goal of why I created this issue. Thanks!

**Comment by cjwebb** [comment]
I can confirm that it is working with 1.4.0-M4
